version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: springjdbc
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"